version: "3"

services:
  nignx:
    image: codershisho/nginx:1.25.0
    container_name: nginx-${PROJECT_NAME}
    tty: true
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:${PUBLIC_FOLDER}
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - php

  php:
    image: codershisho/php
    container_name: php-${PROJECT_NAME}
    tty: true
    volumes:
      - .:${PUBLIC_FOLDER}
    ports:
      - ${PHP_PORT}:5173
    environment:
      TZ: ${TIME_ZONE}

  db:
    image: mariadb:10.9
    container_name: mariadb-${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    restart: always
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}

  echo-server:
    image: codershisho/echo-server:18.18.0-alpine
    container_name: echo-server-${PROJECT_NAME}
    ports:
      - 6001:6001
    command: laravel-echo-server start
    volumes:
      - .:/work
    working_dir: /work

  redis:
    image: redis:latest
    container_name: redis-${PROJECT_NAME}
    ports:
      - 6379:6379
    volumes:
      - ./db_data:/data"
volumes:
  db_data:
